name: Render Quarto Book

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pyyaml

      - name: Skip if last commit was from github-actions
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          if [ "$AUTHOR" = "github-actions" ]; then
            echo "🛑 Last commit was from github-actions. Skipping to avoid loop."
            exit 0
          fi

      - name: Clean docs folder
        run: |
          rm -rf docs/*
          touch docs/.nojekyll

      - name: Render Quarto book
        run: quarto render --output-dir docs

      - name: Commit rendered HTML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "✅ No updates to publish – skipping commit."
          else
            git commit -m "Auto-rendered Quarto book"
            git push
          fi
