name: Render Quarto Book

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.46"  # Match your local version if different

      - name: Set up Python (Optional for now)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Render book (eval is false, so it won’t run code)
        run: quarto render

      - name: Commit rendered HTML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          git diff --quiet || git commit -m "Auto-render Quarto book"
          git push
